// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHXJmx1O-VHMjK_9kJSHsXknuAfjDyJY0',
    appId: '1:347945535740:web:3d0bbd8b6bd6887e272f79',
    messagingSenderId: '347945535740',
    projectId: 'omers-mobileapp-msc',
    authDomain: 'omers-mobileapp-msc.firebaseapp.com',
    storageBucket: 'omers-mobileapp-msc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6gifVUqXNBjLU_1qwQuO7punAqVBBGiU',
    appId: '1:347945535740:android:9e5827af47916ace272f79',
    messagingSenderId: '347945535740',
    projectId: 'omers-mobileapp-msc',
    storageBucket: 'omers-mobileapp-msc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqFRlYlv8dNcUeaubLxQB7-BPkdQfQkCY',
    appId: '1:347945535740:ios:3a9110a055bb0170272f79',
    messagingSenderId: '347945535740',
    projectId: 'omers-mobileapp-msc',
    storageBucket: 'omers-mobileapp-msc.appspot.com',
    iosClientId: '347945535740-0hv6sbais0bnat79epieo897dgotqjob.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqFRlYlv8dNcUeaubLxQB7-BPkdQfQkCY',
    appId: '1:347945535740:ios:3a9110a055bb0170272f79',
    messagingSenderId: '347945535740',
    projectId: 'omers-mobileapp-msc',
    storageBucket: 'omers-mobileapp-msc.appspot.com',
    iosClientId: '347945535740-0hv6sbais0bnat79epieo897dgotqjob.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );
}
